// content/puppies-static.ts
export const staticPuppies = [
  {
    id: "static-macho1",
    name: "Macho 1",
    title: "Spitz Alemão Anão Branco - Macho 1",
    color: "branco",
    cor: "branco",
    sex: "male",
    gender: "male",
    status: "disponivel",
    breed: "Spitz Alemão Anão",
    size: "mini",
    city: "braganca-paulista",
    state: "SP",
    images: [
      "/filhotes/macho1/1.png",
      "/filhotes/macho1/2.png",
      "/filhotes/macho1/3.png",
      "/filhotes/macho1/4.png",
      "/filhotes/macho1/5.png",
      "/filhotes/macho1/6.png",
      "/filhotes/macho1/7.png",
      "/filhotes/macho1/8.png",
      "/filhotes/macho1/9.png",
      "/filhotes/macho1/10.png"
    ],
    price_cents: 350000,
    priceCents: 350000,
    currency: "BRL",
    description: "Filhote saudável, vacinado e microchipado.",
    birth_date: "2026-01-01",
    nascimento: "2026-01-01",
    availableForShipping: true,
    hasPedigree: true,
    vaccinationStatus: "up-to-date",
    hasMicrochip: true,
    isHighlighted: false,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: false,
    reviewCount: 0,
    averageRating: 0,
    viewCount: 0,
    favoriteCount: 0,
    shareCount: 0,
    inquiryCount: 0,
    seoKeywords: [],
    notes: "Teste de filhote fixo.",
    codigo: "TESTE1"
  }
];
